export const MAIN_ISLAND_OBJECTS = [
  {
    id: 'about-door',
    label: 'About',
    position: { x: -3.2, y: 0, z: -2.8 },
    model: '/models/message-board.glb',
    modelScale: 0.03,
    modelOffsetY: 0.8,
    faceCenter: true,
    modelFacingOffsetY: Math.PI + (85 * Math.PI) / 180,
    placeholderColor: '#4169a8',
    placeholderArgs: [0.8, 1.5, 0.5],
    placeholderGeometry: 'box',
    action: { type: 'overlay', value: 'about' },
    proximityThreshold: 2,
  },
  {
    id: 'projects-door',
    label: 'Projects',
    position: { x: -6.0, y: 0, z: 1.6 },
    model: '/models/standing-desk.glb',
    modelScale: 1.1,
    modelGround: true,
    modelOffsetY: 0.2,
    modelFacingOffsetY: Math.PI,
    faceCenter: true,
    labelOffsetX: -0.35,
    labelOffsetZ: -0.65,
    placeholderColor: '#2f7a52',
    placeholderArgs: [0.8, 1.5, 0.5],
    placeholderGeometry: 'box',
    action: { type: 'projectsScreen' },
    proximityThreshold: 2,
  },
  {
    id: 'mailbox',
    label: 'Contact',
    position: { x: -0.8, y: 0, z: 6.2 },
    model: '/models/mailbox.glb',
    modelScale: 1.9,
    faceCenter: true,
    placeholderColor: '#a24545',
    placeholderArgs: [0.7, 0.8, 0.7],
    placeholderGeometry: 'box',
    action: { type: 'overlay', value: 'contact' },
    proximityThreshold: 2,
  },
  {
    id: 'cv-stand',
    label: 'CV',
    position: { x: 0, y: 0, z: -6.2 },
    model: '/models/file-cabinet.glb',
    modelScale: 0.85,
    modelOffsetY: 0.15,
    faceCenter: true,
    modelFacingOffsetY: -Math.PI / 2,
    placeholderColor: '#8a7d35',
    placeholderArgs: [0.4, 1.0, 0.6],
    placeholderGeometry: 'box',
    action: null,
    proximityThreshold: 2,
  },
  {
    id: 'campfire',
    label: 'Campfire',
    position: { x: 3.6, y: 0, z: 3.6 },
    model: '/models/campfire.glb',
    modelScale: 0.75,
    modelOffsetY: 0.55,
    faceCenter: true,
    placeholderColor: '#ad6536',
    placeholderArgs: [0.45, 24, 24],
    placeholderGeometry: 'sphere',
    action: { type: 'toggleDarkMode' },
    proximityThreshold: 2,
  },
  {
    id: 'projects-view-portal',
    label: 'Projects View',
    position: { x: -5.4, y: 0, z: 0.2 },
    model: null,
    placeholderColor: '#3d6ea5',
    placeholderGeometry: 'torus',
    action: { type: 'teleport', value: 'projects' },
    proximityThreshold: 2,
  },
  {
    id: 'exploration-door',
    label: 'Explore',
    position: { x: 4.4, y: 0, z: -4.4 },
    model: null,
    faceCenter: true,
    placeholderColor: '#5a4d9f',
    placeholderArgs: [0.8, 1.5, 0.5],
    placeholderGeometry: 'box',
    action: { type: 'overlay', value: 'exploration' },
    proximityThreshold: 2,
  },
]

export const PROJECTS_ISLAND_OBJECTS = [
  {
    id: 'back-portal',
    label: '⟵ Return',
    position: { x: -4, y: 0, z: 0 },
    model: null,
    placeholderColor: '#4b88ff',
    placeholderGeometry: 'torus',
    action: { type: 'teleport', value: 'main' },
    proximityThreshold: 2,
  },
]

export const PROJECTS = [
  {
    id: 'weather-spotify',
    name: 'Weather Spotify',
    description: 'Generates Spotify playlists based on current weather conditions.',
    tech: ['Python', 'Spotify API', 'OpenWeatherMap'],
    github: 'https://github.com/Vinvin00/weather-spotify-playlist',
    islandPosition: { x: 2, y: 0, z: 0 },
    model: null,
    placeholderColor: '#2f7981',
    placeholderArgs: [0.9, 1.5, 0.6],
    placeholderGeometry: 'box',
    proximityThreshold: 2,
  },
]
